// <auto-generated />
using System;
using AnimalService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalService.Data.Migrations
{
    [DbContext(typeof(AnimalDbContext))]
    [Migration("20240610081423_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalService.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ab0a2c9-8057-4ddb-b3c0-1d1309d8abf3"),
                            Age = 2,
                            Breed = "Double doodle",
                            Color = "White",
                            CoverImageUrl = "https://placedog.net/500",
                            CreatedAt = new DateTime(2024, 6, 10, 8, 14, 22, 728, DateTimeKind.Utc).AddTicks(1553),
                            Description = "lorem ipsum",
                            Name = "Dee Dee",
                            PublicId = 1,
                            Sex = "Female",
                            Status = 0,
                            Type = "Dog",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 14, 22, 728, DateTimeKind.Utc).AddTicks(1555),
                            Weight = 10
                        },
                        new
                        {
                            Id = new Guid("3209988b-c0f2-4328-9b67-358f1028182d"),
                            Age = 5,
                            Breed = "Bengal cat",
                            Color = "Beige",
                            CoverImageUrl = "https://placekitten.com/200/200",
                            CreatedAt = new DateTime(2024, 6, 10, 8, 14, 22, 728, DateTimeKind.Utc).AddTicks(2005),
                            Description = "lorem ipsum",
                            Name = "Buttercup",
                            PublicId = 2,
                            Sex = "Male",
                            Status = 0,
                            Type = "Cat",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 14, 22, 728, DateTimeKind.Utc).AddTicks(2007),
                            Weight = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
